namespace VitalMinds.Clinic.Api.Domain.Enums;

public enum EpisodeState
{
    CREADO,
    EVAL_PSICO_EN_PROCESO,
    DERIVADO_A_MEDICO,
    EVAL_PSICO_OK_SIN_DERIVACION,
    PEDIDO_LAB_EMITIDO,
    EXTRACCION_PROGRAMADA,
    MUESTRAS_EN_RUTA,
    ANALISIS_EN_PROCESO,
    RESULTADOS_DISPONIBLES,
    INFORME_INTEGRADO_LISTO,
    PROPUESTA_EMITIDA,
    SEGUIMIENTO,
    CERRADO
}
